"""Make lead names and email nullable, add store columns

Revision ID: 62f0f7f91a41
Revises: 890988fbba88
Create Date: 2026-07-25 13:57:22.775213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f0f7f91a41'
down_revision: Union[str, None] = '890988fbba88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('store_name', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('city_area', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('address', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('leads', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('leads', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('leads', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('uq_leads_user_email', 'leads', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_leads_user_email', 'leads', ['user_id', 'email'])
    op.alter_column('leads', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('leads', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('leads', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('leads', 'notes')
    op.drop_column('leads', 'address')
    op.drop_column('leads', 'city_area')
    op.drop_column('leads', 'store_name')
    # ### end Alembic commands ###
