"""Add media columns to sequences

Revision ID: 890988fbba88
Revises: 20260527_lead_wa_stat
Create Date: 2026-07-25 13:06:51.936761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890988fbba88'
down_revision: Union[str, None] = '20260527_lead_wa_stat'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_emails_resend_id'), 'emails', ['resend_id'], unique=False)
    op.add_column('sequences', sa.Column('mediatype', sa.String(), nullable=True))
    op.add_column('sequences', sa.Column('mimetype', sa.String(), nullable=True))
    op.add_column('sequences', sa.Column('media', sa.Text(), nullable=True))
    op.add_column('sequences', sa.Column('caption', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequences', 'caption')
    op.drop_column('sequences', 'media')
    op.drop_column('sequences', 'mimetype')
    op.drop_column('sequences', 'mediatype')
    op.drop_index(op.f('ix_emails_resend_id'), table_name='emails')
    # ### end Alembic commands ###
