"""Add poll_question and poll_options to Sequence

Revision ID: dd8e2b2e2b80
Revises: 62f0f7f91a41
Create Date: 2026-07-25 20:24:44.046258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd8e2b2e2b80'
down_revision: Union[str, None] = '62f0f7f91a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequences', sa.Column('poll_question', sa.String(length=255), nullable=True))
    op.add_column('sequences', sa.Column('poll_options', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequences', 'poll_options')
    op.drop_column('sequences', 'poll_question')
    # ### end Alembic commands ###
